<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../jeugdcrossdata/Services/CompetitionDataMerger.cs" Link="CompetitionDataMerger.cs" />
    <Compile Include="../../jeugdcrossdata/Services/GitHubUploader.cs" Link="GitHubUploader.cs" />
    <Compile Include="../../jeugdcrossdata/Services/GitHubTokenInvalidException.cs" Link="GitHubTokenInvalidException.cs" />
  </ItemGroup>
</Project>
